/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Desktop;

import Controller.DBHandlerGetter;
import Controller.DBHandlerSetter;
import Domain.Classies.Customer;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sakis
 */
public class Customerlogin extends javax.swing.JFrame {
    private mainwindow myfather;
    private DefaultListModel customerlistModel;

    /**
     * Creates new form Customerlogin
     */
    public Customerlogin(mainwindow mw) {
        super("Customer login");
        this.myfather = mw;
        initComponents();
        myInit();
    }
    
    private void myInit(){
        this.jlogin.setSelected(true);
        customerlistModel = new DefaultListModel();
    }
    
    private boolean CheckName(){
        this.jLnamefield.setBorder(null);
        this.jFnamefield.setBorder(null);
        this.jIDfield.setBorder(null);
        if(this.jLnamefield.getText().equals(""))
            this.jLnamefield.setBorder(BorderFactory.createLineBorder(Color.red));
        
        if(this.jFnamefield.getText().equals(""))
            this.jFnamefield.setBorder(BorderFactory.createLineBorder(Color.red));
        
        if(this.jIDfield.getText().equals(""))
            this.jIDfield.setBorder(BorderFactory.createLineBorder(Color.red));
        
        if(this.jLnamefield.getText().equals("") || this.jFnamefield.getText().equals("") || this.jIDfield.getText().equals(""))
            return false;
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGroupbutton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jlogin = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jSignup = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jSearchfield = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLnamefield = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jFnamefield = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jGender = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jIDfield = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPhonefield = new javax.swing.JTextField();
        jClear = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jCancel = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 4));

        jPanel5.setMaximumSize(new java.awt.Dimension(120, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel5.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        jGroupbutton.add(jlogin);
        jlogin.setText("Log In");
        jlogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlogin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jlogin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jlogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        jPanel4.add(jlogin);

        jPanel7.setMaximumSize(new java.awt.Dimension(120, 50));
        jPanel7.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel7.setName(""); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel7);

        jGroupbutton.add(jSignup);
        jSignup.setText("Sign Up");
        jSignup.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jSignup.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jSignup.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jSignup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSignupActionPerformed(evt);
            }
        });
        jPanel4.add(jSignup);

        jPanel6.setMaximumSize(new java.awt.Dimension(120, 50));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);

        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

        jSearchfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jSearchfield.setText("Search_Customer");
        jSearchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchfieldActionPerformed(evt);
            }
        });

        jSearch.setText("Search");
        jSearch.setToolTipText("Search Customers by { ID, IDnumber, First name, Last name }");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jList1.setVisibleRowCount(6);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jSearchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jSearch)))
                .addGap(42, 42, 42))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSearchfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, java.awt.BorderLayout.WEST);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setText("Last Name :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel11.add(jLabel2);

        jLnamefield.setEnabled(false);
        jPanel11.add(jLnamefield);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        jLabel3.setText("First Name :");
        jPanel12.add(jLabel3);

        jFnamefield.setEnabled(false);
        jPanel12.add(jFnamefield);

        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jLabel4.setText("Gender :");
        jPanel9.add(jLabel4);

        jGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Male", "Female" }));
        jGender.setEnabled(false);
        jPanel9.add(jGender);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2));

        jLabel5.setText("ID Number :");
        jPanel13.add(jLabel5);

        jIDfield.setEnabled(false);
        jPanel13.add(jIDfield);

        jPanel14.setLayout(new java.awt.GridLayout(1, 2));

        jLabel6.setText("Telephone :");
        jPanel14.add(jLabel6);

        jPhonefield.setEnabled(false);
        jPanel14.add(jPhonefield);

        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jClear)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel15.setMaximumSize(new java.awt.Dimension(32767, 70));
        jPanel15.setPreferredSize(new java.awt.Dimension(833, 50));

        jCancel.setText("Cancel");
        jCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });
        jPanel15.add(jCancel);

        jPanel16.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel16);

        jOK.setText("OK");
        jOK.setToolTipText("");
        jOK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });
        jPanel15.add(jOK);

        jPanel3.add(jPanel15, java.awt.BorderLayout.SOUTH);
        jPanel15.getAccessibleContext().setAccessibleParent(jLabel1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // action enable
        this.jSearch.setEnabled(true);
        this.jSearchfield.setEnabled(true);
        this.jList1.setEnabled(true);

        // action disable
        this.jLnamefield.setEnabled(false);
        this.jFnamefield.setEnabled(false);
        this.jGender.setEnabled(false);
        this.jIDfield.setEnabled(false);
        this.jPhonefield.setEnabled(false);
        
    }//GEN-LAST:event_jloginActionPerformed

    private void jSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSignupActionPerformed
        // action enable
        this.jLnamefield.setEnabled(true);
        this.jFnamefield.setEnabled(true);
        this.jGender.setEnabled(true);
        this.jIDfield.setEnabled(true);
        this.jPhonefield.setEnabled(true);
        
        // action disable
        this.jSearch.setEnabled(false);
        this.jSearchfield.setEnabled(false);
        this.jList1.setEnabled(false);
    }//GEN-LAST:event_jSignupActionPerformed

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        // return Customer
        int joption = 0;
        if(this.jlogin.isSelected()){
            if(!this.jList1.isSelectionEmpty()){
                System.out.println(customerlistModel.getElementAt(this.jList1.getSelectedIndex()));
                this.myfather.addCustomer((Customer)customerlistModel.getElementAt(this.jList1.getSelectedIndex()));
            }else{
                JOptionPane.showMessageDialog(null, "You have to select a customer first", "Alert", JOptionPane.ERROR_MESSAGE);
                joption = 1;
            }
        }else if(this.jSignup.isSelected()){
            if(CheckName()){                
               int id = DBHandlerSetter.addCustomer(new Customer(this.jLnamefield.getText(),this.jFnamefield.getText(),(String)this.jGender.getSelectedItem(),this.jIDfield.getText(),this.jPhonefield.getText()));
               this.myfather.addCustomer(new Customer(id,this.jLnamefield.getText(),this.jFnamefield.getText(),(String)this.jGender.getSelectedItem(),this.jIDfield.getText(),this.jPhonefield.getText()));
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Last Name or First Name or ID number", "Alert", JOptionPane.ERROR_MESSAGE);
                joption = 1;
            }
        }
        if(joption == 0)
            this.dispose();
            
    }//GEN-LAST:event_jOKActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // Clear
        this.jSearchfield.setText("Search_Customer");
        customerlistModel.clear();
        this.jLnamefield.setText("");
        this.jFnamefield.setText("");
        this.jGender.setSelectedIndex(0);
        this.jIDfield.setText("");
        this.jPhonefield.setText("");
        this.jLnamefield.setBorder(null);
        this.jFnamefield.setBorder(null);
        this.jIDfield.setBorder(null);
        
    }//GEN-LAST:event_jClearActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // Search Customer
        customerlistModel.clear();
        List<Customer> customersid;
        customersid = DBHandlerGetter.getCustomer(this.jSearchfield.getText());
        if(!customersid.isEmpty()){
            for(Customer c: customersid)
                customerlistModel.addElement(c);
            this.jList1.setModel(customerlistModel);
        }else{
            JOptionPane.showMessageDialog(null, "Can't find customer `"+this.jSearchfield.getText()+"`.", "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jSearchActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        // exit
        this.dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // customer toolString
        if(!jList1.isSelectionEmpty()){
            Customer c = (Customer)customerlistModel.getElementAt(this.jList1.getSelectedIndex()); 
            jList1.setToolTipText(c.toolString());
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jSearchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchfieldActionPerformed
        this.jSearchActionPerformed(evt);
    }//GEN-LAST:event_jSearchfieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancel;
    private javax.swing.JButton jClear;
    private javax.swing.JTextField jFnamefield;
    private javax.swing.JComboBox<String> jGender;
    private javax.swing.ButtonGroup jGroupbutton;
    private javax.swing.JTextField jIDfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JTextField jLnamefield;
    private javax.swing.JButton jOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jPhonefield;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSearch;
    private javax.swing.JTextField jSearchfield;
    private javax.swing.JRadioButton jSignup;
    private javax.swing.JRadioButton jlogin;
    // End of variables declaration//GEN-END:variables
}
