/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Desktop;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author sakis
 */
public class mainwindow extends javax.swing.JFrame {
    private DateFormat displayFormat;
    private DateFormatter displayFormatter;
    private DateFormat editFormat;
    private DateFormatter editFormatter;
    private DefaultFormatterFactory factory;

    /**
     * Creates new form mainwindow
     */
    public mainwindow() {
        myInit();
        initComponents();
    }
    
    public void myInit(){
        displayFormat = new SimpleDateFormat("dd--MMMM--yyyy");
        displayFormatter = new DateFormatter(displayFormat);
        editFormat = new SimpleDateFormat("dd/MM/yyyy");
        editFormatter = new DateFormatter(editFormat);
        factory = new DefaultFormatterFactory(displayFormatter, displayFormatter, editFormatter);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jBookingpanel = new javax.swing.JPanel();
        jBookpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBookinglist = new javax.swing.JList<>();
        jButtonpanel = new javax.swing.JPanel();
        jConfirm = new javax.swing.JButton();
        jClearbutton = new javax.swing.JButton();
        jTypepanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckintext = new JFormattedTextField(factory, new Date());
        jCheckouttext = new javax.swing.JFormattedTextField(factory, new Date());
        jRoompanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jAddroom = new javax.swing.JButton();
        jRemoveroom = new javax.swing.JButton();
        jCustomerpanel = new javax.swing.JPanel();
        jCustomer = new javax.swing.JLabel();
        jaddcustomer = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBookingpanel.setLayout(new java.awt.BorderLayout(10, 10));

        jBookpanel.setLayout(new javax.swing.BoxLayout(jBookpanel, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(57, 10));
        jLabel1.setMinimumSize(new java.awt.Dimension(10, 10));
        jLabel1.setPreferredSize(new java.awt.Dimension(57, 50));
        jBookpanel.add(jLabel1);

        jBookinglist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jBookinglist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBookinglist.setPreferredSize(new java.awt.Dimension(100, 300));
        jScrollPane1.setViewportView(jBookinglist);

        jBookpanel.add(jScrollPane1);

        jButtonpanel.setLayout(new java.awt.GridLayout(1, 2));

        jConfirm.setText("Confirm");
        jConfirm.setPreferredSize(new java.awt.Dimension(30, 50));
        jButtonpanel.add(jConfirm);

        jClearbutton.setText("Clear");
        jButtonpanel.add(jClearbutton);

        jBookpanel.add(jButtonpanel);

        jBookingpanel.add(jBookpanel, java.awt.BorderLayout.WEST);

        jTypepanel.setLayout(new javax.swing.BoxLayout(jTypepanel, javax.swing.BoxLayout.PAGE_AXIS));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(79, 27));
        jTypepanel.add(jComboBox1);

        jCheckintext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCheckintext.setToolTipText("Check in");
        jTypepanel.add(jCheckintext);

        jCheckouttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTypepanel.add(jCheckouttext);

        jLabel2.setText("Room");
        jRoompanel.add(jLabel2);

        jAddroom.setText("+");
        jRoompanel.add(jAddroom);

        jRemoveroom.setText("-");
        jRoompanel.add(jRemoveroom);

        jTypepanel.add(jRoompanel);

        jCustomer.setText("Customer");
        jCustomerpanel.add(jCustomer);
        jCustomer.getAccessibleContext().setAccessibleName("Customer");

        jaddcustomer.setText("+");
        jCustomerpanel.add(jaddcustomer);

        jTypepanel.add(jCustomerpanel);

        jBookingpanel.add(jTypepanel, java.awt.BorderLayout.EAST);

        jTabbedPane2.addTab("Reservtion", jBookingpanel);
        jTabbedPane2.addTab("Edit", jTabbedPane3);
        jTabbedPane2.addTab("Check in/out", jTabbedPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddroom;
    private javax.swing.JList<String> jBookinglist;
    private javax.swing.JPanel jBookingpanel;
    private javax.swing.JPanel jBookpanel;
    private javax.swing.JPanel jButtonpanel;
    private javax.swing.JFormattedTextField jCheckintext;
    private javax.swing.JFormattedTextField jCheckouttext;
    private javax.swing.JButton jClearbutton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton jConfirm;
    private javax.swing.JLabel jCustomer;
    private javax.swing.JPanel jCustomerpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jRemoveroom;
    private javax.swing.JPanel jRoompanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JPanel jTypepanel;
    private javax.swing.JButton jaddcustomer;
    // End of variables declaration//GEN-END:variables
}
