/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Desktop;

import Controller.DBHandlerGetter;
import Controller.DBHandlerSetter;
import Domain.Classies.Booking;
import Domain.Classies.Customer;
import Domain.Classies.Room;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author sakis
 */
public class mainwindow extends javax.swing.JFrame {
    private DateFormat displayFormat;
    private DateFormatter displayFormatter;
    private DateFormat editFormat;
    private DateFormatter editFormatter;
    private DefaultFormatterFactory factory;
    
    private Customer customer;
    private List<Room> rooms = new ArrayList();
    private List<Booking> books;
    private DefaultListModel booklistModel;
    private DefaultListModel modifyroomlistModel;
    private DefaultListModel listModel;
    private DefaultListModel roomlistModel;
    private DefaultListModel roomlistModel2;
    private DefaultListModel checklistmodel;
    private static final int days = 5;
    
    private List<Room> r1;
    private List<Room> r2;

    /**
     * Creates new form mainwindow
     */
    public mainwindow() {
        super("Hotel System");
        myInit();
        initComponents();        
    }
    
    public void myInit(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../../icon.png")));
        displayFormat = new SimpleDateFormat("dd--MMMM--yyyy");
        displayFormatter = new DateFormatter(displayFormat);
        editFormat = new SimpleDateFormat("dd/MM/yyyy");
        editFormatter = new DateFormatter(editFormat);
        factory = new DefaultFormatterFactory(editFormatter, displayFormatter, editFormatter);
        listModel = new DefaultListModel();
        roomlistModel = new DefaultListModel();
        roomlistModel2 = new DefaultListModel();
        booklistModel = new DefaultListModel();
        modifyroomlistModel = new DefaultListModel();
        checklistmodel = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkgroup = new javax.swing.ButtonGroup();
        jCheckTab = new javax.swing.JTabbedPane();
        jBookingpanel = new javax.swing.JPanel();
        jBookpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBookinglist = new javax.swing.JList<>();
        jButtonpanel = new javax.swing.JPanel();
        jClearbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jConfirm = new javax.swing.JButton();
        jTypepanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jType = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jCheckintext = new JFormattedTextField(factory, new Date());
        jPanel5 = new javax.swing.JPanel();
        jCheckouttext = new javax.swing.JFormattedTextField(factory, new Date());
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jSearchroom = new javax.swing.JButton();
        jRemoveroom = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jCustomerbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jCustomertext = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jEditpanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jmodifySearchtext = new javax.swing.JTextField();
        jmodifySearch = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jmodifyBooklist = new javax.swing.JList<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jmodifyRoomlist = new javax.swing.JList<>();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jmodifyClear = new javax.swing.JButton();
        jmodifyCancel = new javax.swing.JButton();
        jmodifyModify = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jmodifyRBenefits = new javax.swing.JTextPane();
        jCheckinoutpanel = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jcheckSearch = new javax.swing.JTextField();
        jPanel39 = new javax.swing.JPanel();
        jcheckSearchbutton = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jcheckList = new javax.swing.JList<>();
        jPanel26 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jcheckCheckin = new javax.swing.JRadioButton();
        jPanel36 = new javax.swing.JPanel();
        jcheckCheckout = new javax.swing.JRadioButton();
        jPanel38 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jcheckinoutbutton = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jcheckTextpane = new javax.swing.JTextPane();
        jPanel24 = new javax.swing.JPanel();
        jcheckClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckTab.setToolTipText("");

        jBookingpanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBookingpanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBookingpanel.setLayout(new java.awt.BorderLayout(10, 10));

        jBookpanel.setLayout(new javax.swing.BoxLayout(jBookpanel, javax.swing.BoxLayout.PAGE_AXIS));

        jBookinglist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jBookinglist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBookinglist.setVisibleRowCount(15);
        jScrollPane1.setViewportView(jBookinglist);

        jBookpanel.add(jScrollPane1);

        jButtonpanel.setMaximumSize(new java.awt.Dimension(32767, 60));
        jButtonpanel.setMinimumSize(new java.awt.Dimension(204, 40));
        jButtonpanel.setPreferredSize(new java.awt.Dimension(204, 40));
        jButtonpanel.setLayout(new java.awt.GridLayout(1, 0));

        jClearbutton.setText("Clear");
        jClearbutton.setToolTipText("Clear the fields");
        jClearbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jClearbutton.setMaximumSize(new java.awt.Dimension(49, 50));
        jClearbutton.setName(""); // NOI18N
        jClearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearbuttonActionPerformed(evt);
            }
        });
        jButtonpanel.add(jClearbutton);

        jPanel1.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jButtonpanel.add(jPanel1);

        jConfirm.setText("Confirm");
        jConfirm.setToolTipText("Confirm the reservation");
        jConfirm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmActionPerformed(evt);
            }
        });
        jButtonpanel.add(jConfirm);

        jBookpanel.add(jButtonpanel);

        jBookingpanel.add(jBookpanel, java.awt.BorderLayout.CENTER);

        jTypepanel.setPreferredSize(new java.awt.Dimension(200, 313));
        jTypepanel.setLayout(new javax.swing.BoxLayout(jTypepanel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jTypepanel.add(jPanel2);

        jType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Quad", "Suite", "SyperLux" }));
        jType.setToolTipText("Select the type of room");
        jType.setMaximumSize(new java.awt.Dimension(115, 27));
        jTypepanel.add(jType);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 12));
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 12));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 12));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jTypepanel.add(jPanel4);

        jCheckintext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCheckintext.setToolTipText("Check in");
        jCheckintext.setMaximumSize(new java.awt.Dimension(150, 40));
        jCheckintext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckintextKeyPressed(evt);
            }
        });
        jTypepanel.add(jCheckintext);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 7));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 7));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 7));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jTypepanel.add(jPanel5);

        jCheckouttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCheckouttext.setToolTipText("Check out");
        jCheckouttext.setMaximumSize(new java.awt.Dimension(150, 40));
        jCheckouttext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckouttextKeyPressed(evt);
            }
        });
        jTypepanel.add(jCheckouttext);

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Room");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel3);

        jSearchroom.setText("Search");
        jSearchroom.setToolTipText("Search for room availability");
        jSearchroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchroomActionPerformed(evt);
            }
        });
        jPanel9.add(jSearchroom);

        jRemoveroom.setText("Remove");
        jRemoveroom.setToolTipText("Remove room choice");
        jRemoveroom.setMaximumSize(new java.awt.Dimension(25, 29));
        jRemoveroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveroomActionPerformed(evt);
            }
        });
        jPanel9.add(jRemoveroom);

        jPanel6.add(jPanel9);

        jTypepanel.add(jPanel6);

        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 12));
        jPanel12.setMinimumSize(new java.awt.Dimension(100, 12));
        jPanel12.setPreferredSize(new java.awt.Dimension(150, 12));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jTypepanel.add(jPanel12);

        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 50));

        jCustomerbutton.setText("Customer");
        jCustomerbutton.setToolTipText("Select customer");
        jCustomerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jCustomerbutton)
                .addGap(37, 37, 37))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCustomerbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTypepanel.add(jPanel11);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(108, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jCustomertext.setEditable(false);
        jCustomertext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jCustomertext.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jCustomertext.setEnabled(false);
        jScrollPane5.setViewportView(jCustomertext);

        jPanel3.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jTypepanel.add(jPanel3);

        jBookingpanel.add(jTypepanel, java.awt.BorderLayout.EAST);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reservation");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(57, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(10, 10));
        jLabel1.setPreferredSize(new java.awt.Dimension(57, 50));
        jBookingpanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jCheckTab.addTab("Reservation", jBookingpanel);

        jEditpanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jEditpanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel8.setMinimumSize(new java.awt.Dimension(100, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(552, 50));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View / Modify / Cancel");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setMaximumSize(new java.awt.Dimension(220, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(220, 50));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel13.setMaximumSize(new java.awt.Dimension(700, 2147483647));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());

        jmodifySearchtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmodifySearchtext.setText("Search_Booking");
        jmodifySearchtext.setToolTipText("Type * for display all");
        jmodifySearchtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodifySearchtextActionPerformed(evt);
            }
        });
        jPanel14.add(jmodifySearchtext, java.awt.BorderLayout.CENTER);

        jmodifySearch.setText("Search");
        jmodifySearch.setToolTipText("Search Bookings by anything");
        jmodifySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodifySearchActionPerformed(evt);
            }
        });
        jPanel14.add(jmodifySearch, java.awt.BorderLayout.EAST);

        jPanel13.add(jPanel14, java.awt.BorderLayout.NORTH);

        jPanel15.setLayout(new java.awt.GridLayout(1, 1, 0, 100));

        jmodifyBooklist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jmodifyBooklist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmodifyBooklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmodifyBooklistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jmodifyBooklist);

        jPanel15.add(jScrollPane2);

        jPanel13.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel16.setPreferredSize(new java.awt.Dimension(300, 159));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Rooms");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setMaximumSize(new java.awt.Dimension(10, 27));
        jLabel6.setMinimumSize(new java.awt.Dimension(10, 27));
        jLabel6.setPreferredSize(new java.awt.Dimension(10, 29));
        jPanel17.add(jLabel6, java.awt.BorderLayout.PAGE_END);

        jPanel16.add(jPanel17, java.awt.BorderLayout.NORTH);

        jPanel19.setLayout(new java.awt.GridLayout(1, 1));

        jmodifyRoomlist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jmodifyRoomlist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmodifyRoomlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmodifyRoomlistMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jmodifyRoomlist);

        jPanel19.add(jScrollPane3);

        jPanel16.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel16, java.awt.BorderLayout.EAST);

        jPanel7.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel18.setMaximumSize(new java.awt.Dimension(276, 50));
        jPanel18.setPreferredSize(new java.awt.Dimension(276, 40));
        jPanel18.setLayout(new java.awt.GridLayout(1, 0));

        jPanel20.setLayout(new java.awt.BorderLayout());

        jmodifyClear.setText("Clear");
        jmodifyClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodifyClearActionPerformed(evt);
            }
        });
        jPanel20.add(jmodifyClear, java.awt.BorderLayout.WEST);

        jmodifyCancel.setText("Cancel");
        jmodifyCancel.setToolTipText("Cancel Reservation");
        jmodifyCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodifyCancelActionPerformed(evt);
            }
        });
        jPanel20.add(jmodifyCancel, java.awt.BorderLayout.EAST);

        jmodifyModify.setText("Modify");
        jmodifyModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodifyModifyActionPerformed(evt);
            }
        });
        jPanel20.add(jmodifyModify, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel20);

        jPanel21.setLayout(new java.awt.BorderLayout());

        jmodifyRBenefits.setEditable(false);
        jmodifyRBenefits.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jmodifyRBenefits.setEnabled(false);
        jScrollPane4.setViewportView(jmodifyRBenefits);

        jPanel21.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel21);

        jPanel7.add(jPanel18, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout jEditpanelLayout = new javax.swing.GroupLayout(jEditpanel);
        jEditpanel.setLayout(jEditpanelLayout);
        jEditpanelLayout.setHorizontalGroup(
            jEditpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jEditpanelLayout.setVerticalGroup(
            jEditpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        jCheckTab.addTab("View / Modify / Cancel", jEditpanel);

        jCheckinoutpanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jCheckinoutpanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jCheckinoutpanel.setLayout(new java.awt.BorderLayout());

        jPanel23.setPreferredSize(new java.awt.Dimension(0, 40));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Check in/out");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel23.add(jLabel2, java.awt.BorderLayout.CENTER);

        jCheckinoutpanel.add(jPanel23, java.awt.BorderLayout.NORTH);

        jPanel25.setLayout(new java.awt.BorderLayout());

        jPanel27.setLayout(new java.awt.BorderLayout());

        jPanel28.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel28.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanel28.setLayout(new javax.swing.BoxLayout(jPanel28, javax.swing.BoxLayout.LINE_AXIS));

        jcheckSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcheckSearch.setText("Search_Booking");
        jcheckSearch.setToolTipText("Type * for display all");
        jcheckSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckSearchActionPerformed(evt);
            }
        });
        jPanel28.add(jcheckSearch);

        jPanel39.setMaximumSize(new java.awt.Dimension(15, 15));
        jPanel39.setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel28.add(jPanel39);

        jcheckSearchbutton.setText("Search");
        jcheckSearchbutton.setToolTipText("Search Check in/out Bookings");
        jcheckSearchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckSearchbuttonActionPerformed(evt);
            }
        });
        jPanel28.add(jcheckSearchbutton);

        jPanel27.add(jPanel28, java.awt.BorderLayout.NORTH);

        jPanel29.setPreferredSize(new java.awt.Dimension(308, 200));
        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.LINE_AXIS));

        jcheckList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jcheckList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcheckList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcheckListMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jcheckList);

        jPanel29.add(jScrollPane6);

        jPanel27.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel25.add(jPanel27, java.awt.BorderLayout.CENTER);

        jPanel26.setPreferredSize(new java.awt.Dimension(250, 233));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel30.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel30.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel30.setPreferredSize(new java.awt.Dimension(250, 30));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel26.add(jPanel30, java.awt.BorderLayout.NORTH);

        jPanel31.setLayout(new javax.swing.BoxLayout(jPanel31, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel32.setMaximumSize(new java.awt.Dimension(98477, 100));
        jPanel32.setPreferredSize(new java.awt.Dimension(335, 80));
        jPanel32.setLayout(new javax.swing.BoxLayout(jPanel32, javax.swing.BoxLayout.LINE_AXIS));

        jPanel37.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel37.setPreferredSize(new java.awt.Dimension(15, 80));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel32.add(jPanel37);

        checkgroup.add(jcheckCheckin);
        jcheckCheckin.setSelected(true);
        jcheckCheckin.setText("Checkin");
        jcheckCheckin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcheckCheckin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jcheckCheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckCheckinActionPerformed(evt);
            }
        });
        jPanel32.add(jcheckCheckin);

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel32.add(jPanel36);

        checkgroup.add(jcheckCheckout);
        jcheckCheckout.setText("Checkout");
        jcheckCheckout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcheckCheckout.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jcheckCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckCheckoutActionPerformed(evt);
            }
        });
        jPanel32.add(jcheckCheckout);

        jPanel38.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel38.setMinimumSize(new java.awt.Dimension(15, 100));
        jPanel38.setPreferredSize(new java.awt.Dimension(15, 80));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel32.add(jPanel38);

        jPanel31.add(jPanel32);

        jcheckinoutbutton.setText("Checkin");
        jcheckinoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckinoutbuttonActionPerformed(evt);
            }
        });
        jPanel33.add(jcheckinoutbutton);

        jPanel31.add(jPanel33);

        jPanel34.setMaximumSize(new java.awt.Dimension(32767, 15));
        jPanel34.setMinimumSize(new java.awt.Dimension(100, 15));
        jPanel34.setPreferredSize(new java.awt.Dimension(250, 15));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel31.add(jPanel34);

        jPanel35.setLayout(new java.awt.BorderLayout());

        jcheckTextpane.setEditable(false);
        jcheckTextpane.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jcheckTextpane.setEnabled(false);
        jScrollPane7.setViewportView(jcheckTextpane);

        jPanel35.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel31.add(jPanel35);

        jPanel26.add(jPanel31, java.awt.BorderLayout.CENTER);

        jPanel25.add(jPanel26, java.awt.BorderLayout.EAST);

        jCheckinoutpanel.add(jPanel25, java.awt.BorderLayout.CENTER);

        jPanel24.setPreferredSize(new java.awt.Dimension(558, 25));
        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.LINE_AXIS));

        jcheckClear.setText("Clear");
        jcheckClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckClearActionPerformed(evt);
            }
        });
        jPanel24.add(jcheckClear);

        jCheckinoutpanel.add(jPanel24, java.awt.BorderLayout.SOUTH);

        jCheckTab.addTab("Check in/out", jCheckinoutpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchroomActionPerformed
        // Search
        AvailableRooms ar = null;
        int option=0;
        r1 = DBHandlerGetter.getSameTypeRoom(this.getComboBoxintType(),this.getReservationChekin(), this.getReservationChekout());
        r1.removeAll(rooms);
        if(!r1.isEmpty()){
            roomlistModel.clear();
            for(Room a : r1)
                roomlistModel.addElement(a.toString());
            AvailableRoomsSameType ars = new AvailableRoomsSameType(this);
            ars.setVisible(true);
        }else{
            option =JOptionPane.showConfirmDialog(null,"None "+ this.getComboBoxType()+ " rooms are available for your dates."
                    + "\nDo you like to see alternative suggestions?", "Alert", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                option = 0;
                r1 = DBHandlerGetter.getAllTypeRoom(this.getReservationChekin(), this.getReservationChekout());
                r1.removeAll(rooms);
                r2 = DBHandlerGetter.getSameTypeRoom(this.getComboBoxintType(), this.getAlternativeCheckin(), this.getAlternativeCheckout());
                if(!r1.isEmpty()){
                    option = 1;
                    roomlistModel.clear();
                    for(Room a : r1)
                        roomlistModel.addElement(a.toString());
                }
                if(!r2.isEmpty()){
                    option = 1;
                    roomlistModel2.clear();
                    for(Room a : r2)
                        roomlistModel2.addElement(a.toString());
                }
                if(option == 1){
                    ar = new AvailableRooms(this);
                    ar.setVisible(true);
                }else
                    JOptionPane.showMessageDialog(null, "None rooms are available for your dates.", "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jSearchroomActionPerformed

    private void jClearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearbuttonActionPerformed
        // Clear
        listModel.clear();
        rooms.clear();
        jType.setSelectedIndex(0);
        jCheckintext.setValue(Date.from(Instant.now()));
        jCheckouttext.setValue(Date.from(Instant.now()));
        jCustomertext.setText("");
        jCustomertext.setBorder(BorderFactory.createLineBorder(Color.red));
    }//GEN-LAST:event_jClearbuttonActionPerformed

    private void jRemoveroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveroomActionPerformed
        // remove
        if(!this.jBookinglist.isSelectionEmpty()){
            rooms.remove(jBookinglist.getSelectedIndex());
           this.listModel.removeElementAt(jBookinglist.getSelectedIndex());           
        }else 
            JOptionPane.showMessageDialog(null, "There is nothing to remove", "Alert", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jRemoveroomActionPerformed

    private void jCustomerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomerbuttonActionPerformed
        // ADD Customer
        Customerlogin cl = new Customerlogin(this);
        cl.setVisible(true);
    }//GEN-LAST:event_jCustomerbuttonActionPerformed
    
    private void jConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmActionPerformed
        // Confirm
        Booking b = new Booking();
        b.setRooms(rooms);
        b.setDate(this.getReservationChekin(), this.getReservationChekout());
        b.setCustomer(customer);
        int option = 0;
        if(customer == null || this.listModel.isEmpty())
            JOptionPane.showMessageDialog(null, "You have to select a customer and room(s) to confirm a reservation!", "Alert", JOptionPane.ERROR_MESSAGE);
        else if(customer != null && !this.listModel.isEmpty()){
            String st = "Dear "+customer.getFname() +" "+customer.getLname() +" do you agree with the following reservation?"
                    + "\nNumber of rooms: "+rooms.size() + " Period: "+ this.jCheckintext.getText() +" to "+ this.jCheckouttext.getText() +" Total cost: $"+b.getTotalCost();
            option = JOptionPane.showConfirmDialog(null, st, "Alert", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                //create booking and restoring to DB
                DBHandlerSetter.addBooking(b);
                System.out.println(b);
                System.out.println("ID:"+b.getBookid());
                st = "Dear "+customer.getFname() +" "+customer.getLname() +" thank you for your choice!\nYour Reservation ID is: "+b.getBookid();
                JOptionPane.showMessageDialog(null, st, "New Reservation", JOptionPane.INFORMATION_MESSAGE);
                this.jClearbuttonActionPerformed(null);
            }
        }
    }//GEN-LAST:event_jConfirmActionPerformed

    private void jBookingpanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBookingpanelAncestorAdded
        // resize
        this.jClearbuttonActionPerformed(null);
        this.setSize(500, 400);
    }//GEN-LAST:event_jBookingpanelAncestorAdded

    private void jEditpanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jEditpanelAncestorAdded
        // resize
        books = new ArrayList();
        this.jmodifyClearActionPerformed(null);
        this.setSize(1000, 400);
    }//GEN-LAST:event_jEditpanelAncestorAdded

    private void jmodifyClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodifyClearActionPerformed
        // Clear the selections
        this.jmodifySearchtext.setText("Search_Booking");
        this.booklistModel.clear();
        this.jmodifyBooklist.setSelectedIndex(-1);
        this.modifyroomlistModel.clear();
        this.jmodifyRoomlist.setSelectedIndex(-1);
        this.jmodifyRBenefits.setText("");
        
    }//GEN-LAST:event_jmodifyClearActionPerformed

    private void jmodifyModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodifyModifyActionPerformed
        // selct a booking for modify
        if(!this.jmodifyBooklist.isSelectionEmpty()){
            
            ModifyBooking mb = new ModifyBooking(books.get(this.jmodifyBooklist.getSelectedIndex()));
            mb.setVisible(true);
        }else
            JOptionPane.showMessageDialog(null, "You have to select booking first.", "Alert", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jmodifyModifyActionPerformed

    private void jCheckouttextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckouttextKeyPressed
        listModel.clear();
        rooms.clear();
    }//GEN-LAST:event_jCheckouttextKeyPressed

    private void jCheckintextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckintextKeyPressed
        listModel.clear();
        rooms.clear();
    }//GEN-LAST:event_jCheckintextKeyPressed

    private void jmodifySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodifySearchActionPerformed
        // Search for booking
        //this.jmodifySearchtext.setText("07/06/2017 to 14/06/2017");
        books = DBHandlerGetter.getBookingByAny(this.jmodifySearchtext.getText());
        if(!books.isEmpty()){
            this.addBookingsforModify();
        }else{
            JOptionPane.showMessageDialog(null, "Can't find booking details with `"+this.jmodifySearchtext.getText()+"`.", "Alert", JOptionPane.ERROR_MESSAGE);
            this.jmodifyClearActionPerformed(null);
        }
    }//GEN-LAST:event_jmodifySearchActionPerformed

    private void jmodifyBooklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmodifyBooklistMouseClicked
        // booking click
        this.jmodifyRBenefits.setText("");
        if(!this.jmodifyBooklist.isSelectionEmpty())
            this.addRoomsforModify(this.jmodifyBooklist.getSelectedIndex());
    }//GEN-LAST:event_jmodifyBooklistMouseClicked

    private void jmodifyRoomlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmodifyRoomlistMouseClicked
        // room click
        this.jmodifyRBenefits.setText("");
        if(!this.jmodifyRoomlist.isSelectionEmpty())
            this.jmodifyRBenefits.setText("Benefits: "+books.get(this.jmodifyBooklist.getSelectedIndex()).getRooms().get(this.jmodifyRoomlist.getSelectedIndex()).Benefits()+"     ");
    }//GEN-LAST:event_jmodifyRoomlistMouseClicked

    private void jmodifyCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodifyCancelActionPerformed
        // delete reservation
        int option = 0;
        if(!this.jmodifyBooklist.isSelectionEmpty()){
            option = JOptionPane.showConfirmDialog(null, "You select to delete booking with booking id: "+books.get(this.jmodifyBooklist.getSelectedIndex()).getBookid()+".\nAre you sure?", "Alert", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                if(DBHandlerSetter.deleteResarvation(books.get(this.jmodifyBooklist.getSelectedIndex()).getBookid())){
                    JOptionPane.showMessageDialog(null, "The booking with booking id: "+books.get(this.jmodifyBooklist.getSelectedIndex()).getBookid()+" is deleted!", "Alert", JOptionPane.INFORMATION_MESSAGE);
                    this.booklistModel.remove(this.jmodifyBooklist.getSelectedIndex());
                    this.modifyroomlistModel.clear();
                }else
                    JOptionPane.showMessageDialog(null, "Problem with DataBase", "Alert", JOptionPane.ERROR_MESSAGE);
            }
        }else
            JOptionPane.showMessageDialog(null, "You have to select booking first.", "Alert", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jmodifyCancelActionPerformed

    private void jmodifySearchtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodifySearchtextActionPerformed
        this.modifyroomlistModel.clear();
        this.jmodifyRBenefits.setText("");
        this.jmodifySearchActionPerformed(null);
    }//GEN-LAST:event_jmodifySearchtextActionPerformed

    private void jcheckSearchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckSearchbuttonActionPerformed
        // Search booking
        this.checklistmodel.clear();
        
        if(this.jcheckCheckin.isSelected()){
            //checkin
            books = DBHandlerGetter.getBookingforCheckin(this.jcheckSearch.getText());
            if(!books.isEmpty()){
                this.addBookingsforCheckinout();
            }else
                JOptionPane.showMessageDialog(null, "Can't find booking details with `"+this.jcheckSearch.getText()+"`.", "Alert", JOptionPane.ERROR_MESSAGE);
        }else{
            //checkout
            books = DBHandlerGetter.getCheckinforCheckout(this.jcheckSearch.getText());
            if(!books.isEmpty()){
                this.addBookingsforCheckinout();
            }else
                JOptionPane.showMessageDialog(null, "Can't find checkin booking details with `"+this.jcheckSearch.getText()+"`.", "Alert", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jcheckSearchbuttonActionPerformed

    private void jcheckClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckClearActionPerformed
        // clear
        this.jcheckSearch.setText("Search_Booking");
        this.jcheckList.clearSelection();
        this.checklistmodel.clear();
        this.jcheckTextpane.setText("");
    }//GEN-LAST:event_jcheckClearActionPerformed

    private void jCheckinoutpanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jCheckinoutpanelAncestorAdded
        // chek in out display
        this.jcheckClearActionPerformed(null);
        this.setSize(624, 400);
    }//GEN-LAST:event_jCheckinoutpanelAncestorAdded

    private void jcheckSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckSearchActionPerformed
        // enter
        this.jcheckSearchbuttonActionPerformed(null);
    }//GEN-LAST:event_jcheckSearchActionPerformed

    private void jcheckListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcheckListMouseClicked
        // show Customer
        if(!this.jcheckList.isSelectionEmpty())
            this.jcheckTextpane.setText(this.books.get(jcheckList.getSelectedIndex()).getCustomer().toolString());
    }//GEN-LAST:event_jcheckListMouseClicked

    private void jcheckCheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckCheckinActionPerformed
        // TODO add your handling code here:
        this.jcheckClearActionPerformed(null);
        this.jcheckinoutbutton.setText("Checkin");
    }//GEN-LAST:event_jcheckCheckinActionPerformed

    private void jcheckCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckCheckoutActionPerformed
        // TODO add your handling code here:
        this.jcheckClearActionPerformed(null);
        this.jcheckinoutbutton.setText("Checkout");
    }//GEN-LAST:event_jcheckCheckoutActionPerformed

    private void jcheckinoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckinoutbuttonActionPerformed
        // Add to database
        if(!this.jcheckList.isSelectionEmpty()){
            if(this.jcheckCheckin.isSelected()){
                DBHandlerSetter.chechin(this.books.get(this.jcheckList.getSelectedIndex()).getBookid());
                JOptionPane.showMessageDialog(null, "The booking with id: "+this.books.get(this.jcheckList.getSelectedIndex()).getBookid()
                        +" has CheckIN!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            }else{
                DBHandlerSetter.chechout(this.books.get(this.jcheckList.getSelectedIndex()));
                JOptionPane.showMessageDialog(null, "The booking with id: "+this.books.get(this.jcheckList.getSelectedIndex()).getBookid()
                        +" has CheckOUT!", "Alert", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else
            JOptionPane.showMessageDialog(null, "You have to select booking first!", "Alert", JOptionPane.ERROR_MESSAGE);
        this.jcheckClearActionPerformed(null);
    }//GEN-LAST:event_jcheckinoutbuttonActionPerformed

    protected void addCustomer(Customer c){
        customer = new Customer(c);
        this.jCustomertext.setText(c.CustomerName()+"\nID number: "+c.getAT());
        this.jCustomertext.setBorder(null);
    }
    protected Booking getBookingformodify(){
        return books.get(this.jmodifyBooklist.getSelectedIndex());
    }
    
    protected void addBookingList(int list,int index){
        if(list == 1){
            rooms.add(r1.get(index));
            if(!rooms.contains(r1.get(index)))
                rooms.add(r1.get(index));
            listModel.clear();
            for(Room a : rooms)
                listModel.addElement(a);

            this.jBookinglist.setModel(listModel);
        }else{
            this.AlternativeResarvation();
            rooms.add(r2.get(index));
            listModel.clear();
            for(Room a : rooms)
                listModel.addElement(a);

            this.jBookinglist.setModel(listModel);
        }
    }
    
    protected String getComboBoxType(){
        return (String) this.jType.getSelectedItem();

    }
    
    public int getComboBoxintType(){
        return this.jType.getSelectedIndex()+1;
    }
    
    protected String getReservationChekin(){
        Date d1 = (Date)this.jCheckintext.getValue();
        String s1 = editFormat.format(new Date(d1.getTime()));
        return s1;
    }
    
    protected String getReservationChekout(){
        Date d1 = (Date)this.jCheckouttext.getValue();
        String s1 = editFormat.format(new Date(d1.getTime()));
        return s1;
    }
    
    protected void AlternativeResarvation(){
        Date d1;
        this.listModel.clear();
        this.rooms= new ArrayList();
        d1 = (Date)this.jCheckintext.getValue();
        d1.setTime(d1.getTime()+days*24*60*60*1000);
        this.jCheckintext.setValue(d1);
        d1 = (Date)this.jCheckouttext.getValue();
        d1.setTime(d1.getTime()+days*24*60*60*1000);
        this.jCheckouttext.setValue(d1);
    }
    
    protected String getAlternativeCheckin(){
        Date d1 = (Date)this.jCheckintext.getValue();
        String s1 = editFormat.format(new Date(d1.getTime()+days*24*60*60*1000));
        return s1;
    }
    
    protected String getAlternativeCheckout(){
        Date d2 = (Date)this.jCheckouttext.getValue();
        String s2 = editFormat.format(new Date(d2.getTime()+days*24*60*60*1000));
        return s2;
    }
    
    protected DefaultListModel getroomlistmodel(){
        return roomlistModel;
    }
    
    protected DefaultListModel getroomlistmodel2(){
        return roomlistModel2;
    }
    
    protected String getBenefits(int list, int i){
        if(list == 1)
            return this.r1.get(i).Benefits();
        else
            return this.r2.get(i).Benefits();
    }
    
    private void addBookingsforModify(){
        booklistModel.clear();
        for(Booking b : books)
            booklistModel.addElement(b);
        
        this.jmodifyBooklist.setModel(booklistModel);
    }
    
    private void addRoomsforModify(int index){
        modifyroomlistModel.clear();
        Booking b = books.get(index);
        for(Room r : b.getRooms())
            modifyroomlistModel.addElement(r);
        
        this.jmodifyRoomlist.setModel(modifyroomlistModel);
    }
    
    private void addBookingsforCheckinout(){
        this.checklistmodel.clear();
        for(Booking b : books)
            checklistmodel.addElement(b.toCheckinout());
        
        this.jcheckList.setModel(checklistmodel);
    }
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup checkgroup;
    private javax.swing.JList<String> jBookinglist;
    private javax.swing.JPanel jBookingpanel;
    private javax.swing.JPanel jBookpanel;
    private javax.swing.JPanel jButtonpanel;
    private javax.swing.JTabbedPane jCheckTab;
    private javax.swing.JPanel jCheckinoutpanel;
    private javax.swing.JFormattedTextField jCheckintext;
    private javax.swing.JFormattedTextField jCheckouttext;
    private javax.swing.JButton jClearbutton;
    private javax.swing.JButton jConfirm;
    private javax.swing.JButton jCustomerbutton;
    private javax.swing.JTextPane jCustomertext;
    private javax.swing.JPanel jEditpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jRemoveroom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton jSearchroom;
    private javax.swing.JComboBox<String> jType;
    private javax.swing.JPanel jTypepanel;
    private javax.swing.JRadioButton jcheckCheckin;
    private javax.swing.JRadioButton jcheckCheckout;
    private javax.swing.JButton jcheckClear;
    private javax.swing.JList<String> jcheckList;
    private javax.swing.JTextField jcheckSearch;
    private javax.swing.JButton jcheckSearchbutton;
    private javax.swing.JTextPane jcheckTextpane;
    private javax.swing.JButton jcheckinoutbutton;
    private javax.swing.JList<String> jmodifyBooklist;
    private javax.swing.JButton jmodifyCancel;
    private javax.swing.JButton jmodifyClear;
    private javax.swing.JButton jmodifyModify;
    private javax.swing.JTextPane jmodifyRBenefits;
    private javax.swing.JList<String> jmodifyRoomlist;
    private javax.swing.JButton jmodifySearch;
    private javax.swing.JTextField jmodifySearchtext;
    // End of variables declaration//GEN-END:variables
}
