/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Desktop;

import java.awt.Color;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
//import java.time.Instant;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author sakis
 */
public class mainwindow extends javax.swing.JFrame {
    private DateFormat displayFormat;
    private DateFormatter displayFormatter;
    private DateFormat editFormat;
    private DateFormatter editFormatter;
    private DefaultFormatterFactory factory;
    
    private DefaultListModel listModel;
    private static final int days = 5;


    /**
     * Creates new form mainwindow
     */
    public mainwindow() {
        myInit();
        initComponents();
    }
    
    public void myInit(){
        displayFormat = new SimpleDateFormat("dd--MMMM--yyyy");
        displayFormatter = new DateFormatter(displayFormat);
        editFormat = new SimpleDateFormat("dd/MM/yyyy");
        editFormatter = new DateFormatter(editFormat);
        factory = new DefaultFormatterFactory(displayFormatter, displayFormatter, editFormatter);
        listModel = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jBookingpanel = new javax.swing.JPanel();
        jBookpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBookinglist = new javax.swing.JList<>();
        jButtonpanel = new javax.swing.JPanel();
        jClearbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jConfirm = new javax.swing.JButton();
        jTypepanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jType = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jCheckintext = new JFormattedTextField(factory, new Date());
        jPanel5 = new javax.swing.JPanel();
        jCheckouttext = new javax.swing.JFormattedTextField(factory, new Date());
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jSearchroom = new javax.swing.JButton();
        jRemoveroom = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jCustomerbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCustomertext = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jEditpanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jmodifySearchtext = new javax.swing.JTextField();
        jmodifySearch = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jmodifyBooklist = new javax.swing.JList<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel18 = new javax.swing.JPanel();
        jmodifyModify = new javax.swing.JButton();
        jmodifyCancel = new javax.swing.JButton();
        jmodifyClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setToolTipText("");

        jBookingpanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBookingpanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBookingpanel.setLayout(new java.awt.BorderLayout(10, 10));

        jBookpanel.setLayout(new javax.swing.BoxLayout(jBookpanel, javax.swing.BoxLayout.PAGE_AXIS));

        jBookinglist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jBookinglist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBookinglist.setVisibleRowCount(15);
        jScrollPane1.setViewportView(jBookinglist);

        jBookpanel.add(jScrollPane1);

        jButtonpanel.setMaximumSize(new java.awt.Dimension(32767, 60));
        jButtonpanel.setLayout(new java.awt.GridLayout(1, 0));

        jClearbutton.setText("Clear");
        jClearbutton.setToolTipText("Clear the fields");
        jClearbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jClearbutton.setMaximumSize(new java.awt.Dimension(49, 50));
        jClearbutton.setName(""); // NOI18N
        jClearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearbuttonActionPerformed(evt);
            }
        });
        jButtonpanel.add(jClearbutton);

        jPanel1.setMaximumSize(new java.awt.Dimension(20, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(20, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jButtonpanel.add(jPanel1);

        jConfirm.setText("Confirm");
        jConfirm.setToolTipText("Confirm the reservation");
        jConfirm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmActionPerformed(evt);
            }
        });
        jButtonpanel.add(jConfirm);

        jBookpanel.add(jButtonpanel);

        jBookingpanel.add(jBookpanel, java.awt.BorderLayout.CENTER);

        jTypepanel.setLayout(new javax.swing.BoxLayout(jTypepanel, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 20));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jTypepanel.add(jPanel2);

        jType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", "Quad", "Suite", "SyperLux" }));
        jType.setToolTipText("Select the type of room");
        jType.setMaximumSize(new java.awt.Dimension(115, 27));
        jTypepanel.add(jType);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 12));
        jPanel4.setMinimumSize(new java.awt.Dimension(100, 12));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 12));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jTypepanel.add(jPanel4);

        jCheckintext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCheckintext.setToolTipText("Check in");
        jCheckintext.setMaximumSize(new java.awt.Dimension(150, 40));
        jTypepanel.add(jCheckintext);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 7));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 7));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 7));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jTypepanel.add(jPanel5);

        jCheckouttext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCheckouttext.setToolTipText("Check out");
        jCheckouttext.setMaximumSize(new java.awt.Dimension(150, 40));
        jTypepanel.add(jCheckouttext);

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Room");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel3);

        jSearchroom.setText("Search");
        jSearchroom.setToolTipText("Search for room availability");
        jSearchroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchroomActionPerformed(evt);
            }
        });
        jPanel9.add(jSearchroom);

        jRemoveroom.setText("Remove");
        jRemoveroom.setToolTipText("Remove room choice");
        jRemoveroom.setMaximumSize(new java.awt.Dimension(25, 29));
        jRemoveroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveroomActionPerformed(evt);
            }
        });
        jPanel9.add(jRemoveroom);

        jPanel6.add(jPanel9);

        jTypepanel.add(jPanel6);

        jPanel12.setMaximumSize(new java.awt.Dimension(32767, 12));
        jPanel12.setMinimumSize(new java.awt.Dimension(100, 12));
        jPanel12.setPreferredSize(new java.awt.Dimension(150, 12));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jTypepanel.add(jPanel12);

        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 50));

        jCustomerbutton.setText("Customer");
        jCustomerbutton.setToolTipText("Select customer");
        jCustomerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustomerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jCustomerbutton)
                .addGap(37, 37, 37))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCustomerbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTypepanel.add(jPanel11);

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(108, 50));

        jCustomertext.setBackground(new java.awt.Color(251, 250, 248));
        jCustomertext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCustomertext.setText("no Customer");
        jCustomertext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCustomertext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCustomertext, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jTypepanel.add(jPanel3);

        jBookingpanel.add(jTypepanel, java.awt.BorderLayout.EAST);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reservation");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(57, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(10, 10));
        jLabel1.setPreferredSize(new java.awt.Dimension(57, 50));
        jBookingpanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane2.addTab("Reservation", jBookingpanel);

        jEditpanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jEditpanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 50));
        jPanel8.setMinimumSize(new java.awt.Dimension(100, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(552, 50));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("View / Modify / Cancel");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setMaximumSize(new java.awt.Dimension(220, 50));
        jLabel4.setPreferredSize(new java.awt.Dimension(220, 50));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setLayout(new java.awt.BorderLayout());

        jmodifySearchtext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jmodifySearchtext.setText("Search Booking");
        jPanel14.add(jmodifySearchtext, java.awt.BorderLayout.CENTER);

        jmodifySearch.setText("Search");
        jPanel14.add(jmodifySearch, java.awt.BorderLayout.EAST);

        jPanel13.add(jPanel14, java.awt.BorderLayout.NORTH);

        jPanel15.setLayout(new java.awt.GridLayout(1, 1, 0, 100));

        jmodifyBooklist.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1 Room 1 Customer 1 Checkin Checkout", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jmodifyBooklist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jmodifyBooklist);

        jPanel15.add(jScrollPane2);

        jPanel13.add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel13);

        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Rooms");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setMaximumSize(new java.awt.Dimension(10, 27));
        jLabel6.setMinimumSize(new java.awt.Dimension(10, 27));
        jLabel6.setPreferredSize(new java.awt.Dimension(10, 29));
        jPanel17.add(jLabel6, java.awt.BorderLayout.PAGE_END);

        jPanel16.add(jPanel17, java.awt.BorderLayout.NORTH);

        jPanel19.setLayout(new java.awt.GridLayout(1, 1));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jPanel19.add(jScrollPane3);

        jPanel16.add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel16);

        jPanel7.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel18.setMaximumSize(new java.awt.Dimension(276, 50));
        jPanel18.setPreferredSize(new java.awt.Dimension(276, 50));

        jmodifyModify.setText("Modify");

        jmodifyCancel.setText("Cancel");

        jmodifyClear.setText("Clear");
        jmodifyClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmodifyClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jmodifyClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jmodifyModify)
                .addGap(49, 49, 49)
                .addComponent(jmodifyCancel)
                .addGap(182, 182, 182))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmodifyModify)
                    .addComponent(jmodifyCancel)
                    .addComponent(jmodifyClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel18, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout jEditpanelLayout = new javax.swing.GroupLayout(jEditpanel);
        jEditpanel.setLayout(jEditpanelLayout);
        jEditpanelLayout.setHorizontalGroup(
            jEditpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        jEditpanelLayout.setVerticalGroup(
            jEditpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("View / Modify / Cancel", jEditpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchroomActionPerformed
        // Search
        AvailableRooms ar = new AvailableRooms(this);
        ar.setVisible(true);
    }//GEN-LAST:event_jSearchroomActionPerformed

    private void jClearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearbuttonActionPerformed
        // Clear
        listModel.clear();
        jType.setSelectedIndex(0);
        //jCheckintext.setValue(Date.from(Instant.now()));
        //jCheckouttext.setValue(Date.from(Instant.now()));
        jCustomertext.setText("no Customer");
        jCustomertext.setBorder(BorderFactory.createLineBorder(Color.red));
    }//GEN-LAST:event_jClearbuttonActionPerformed

    private void jRemoveroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveroomActionPerformed
        // remove
        if(!this.jBookinglist.isSelectionEmpty()){
           this.listModel.removeElementAt(jBookinglist.getSelectedIndex());
        }else 
            JOptionPane.showMessageDialog(null, "There is nothing to remove", "Alert", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jRemoveroomActionPerformed

    private void jCustomerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustomerbuttonActionPerformed
        // ADD Customer
        Customerlogin cl = new Customerlogin(this);
        cl.setVisible(true);
    }//GEN-LAST:event_jCustomerbuttonActionPerformed

    protected void addCustomername(String data){
        this.jCustomertext.setText(data);
        this.jCustomertext.setBorder(null);
    }
    private void jConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConfirmActionPerformed

    private void jBookingpanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBookingpanelAncestorAdded
        // resize
        this.setSize(500, 400);
    }//GEN-LAST:event_jBookingpanelAncestorAdded

    private void jEditpanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jEditpanelAncestorAdded
        // resize
        this.setSize(800, 400);
    }//GEN-LAST:event_jEditpanelAncestorAdded

    private void jmodifyClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmodifyClearActionPerformed
        // Clear the selections
        this.jmodifySearchtext.setText("Search Booking");
        
    }//GEN-LAST:event_jmodifyClearActionPerformed


    

    
    protected void addBookingList(String dataline){
        this.listModel.addElement(dataline);
        this.jBookinglist.setModel(listModel);
    }
    
    protected String getComboBoxType(){
        return (String) this.jType.getSelectedItem();
    }
    
    protected void AlternativeResarvation(){
        this.listModel.clear();
        this.jCheckintext.setValue(new Date(this.getAlternativeCheckin()));
        this.jCheckouttext.setValue(new Date(this.getAlternativeCheckout()));  
    }
    
    protected String getAlternativeCheckin(){
        Date d1 = (Date)this.jCheckintext.getValue();
        String s1 = editFormat.format(new Date(d1.getTime()+days*24*60*60*1000));
        return s1;
    }
    
    protected String getAlternativeCheckout(){
        Date d2 = (Date)this.jCheckouttext.getValue();
        String s2 = editFormat.format(new Date(d2.getTime()+days*24*60*60*1000));
        return s2;
    }
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainwindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainwindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jBookinglist;
    private javax.swing.JPanel jBookingpanel;
    private javax.swing.JPanel jBookpanel;
    private javax.swing.JPanel jButtonpanel;
    private javax.swing.JFormattedTextField jCheckintext;
    private javax.swing.JFormattedTextField jCheckouttext;
    private javax.swing.JButton jClearbutton;
    private javax.swing.JButton jConfirm;
    private javax.swing.JButton jCustomerbutton;
    private javax.swing.JLabel jCustomertext;
    private javax.swing.JPanel jEditpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jRemoveroom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jSearchroom;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> jType;
    private javax.swing.JPanel jTypepanel;
    private javax.swing.JList<String> jmodifyBooklist;
    private javax.swing.JButton jmodifyCancel;
    private javax.swing.JButton jmodifyClear;
    private javax.swing.JButton jmodifyModify;
    private javax.swing.JButton jmodifySearch;
    private javax.swing.JTextField jmodifySearchtext;
    // End of variables declaration//GEN-END:variables
}
