/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Desktop;

/**
 *
 * @author sakis
 */
public class ModifyBooking extends javax.swing.JFrame {

    /**
     * Creates new form ModifyBooking
     */
    public ModifyBooking(String title) {
        super(title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel18 = new javax.swing.JPanel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel20 = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel22 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jReset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modify");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel8.setPreferredSize(new java.awt.Dimension(222, 35));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setText("Room(s)");
        jCheckBox1.setEnabled(false);
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setMaximumSize(new java.awt.Dimension(300, 40));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel8.add(jCheckBox1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1 Single 45$", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jPanel9.add(jScrollPane1);

        jPanel7.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel10.setPreferredSize(new java.awt.Dimension(222, 40));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Remove");
        jPanel10.add(jButton1, java.awt.BorderLayout.WEST);

        jButton2.setText("Add New");
        jPanel10.add(jButton2, java.awt.BorderLayout.EAST);

        jPanel7.add(jPanel10, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel7);

        jPanel6.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jPanel6.setPreferredSize(new java.awt.Dimension(170, 318));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel11.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel11.setPreferredSize(new java.awt.Dimension(222, 35));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11, java.awt.BorderLayout.PAGE_START);

        jPanel12.setMaximumSize(new java.awt.Dimension(200, 20000));
        jPanel12.setMinimumSize(new java.awt.Dimension(150, 148));
        jPanel12.setPreferredSize(new java.awt.Dimension(150, 200));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel15.setPreferredSize(new java.awt.Dimension(222, 100));
        jPanel15.setLayout(new java.awt.GridLayout(2, 0));

        jPanel17.setPreferredSize(new java.awt.Dimension(352, 60));

        jCheckBox2.setText("Check in");
        jCheckBox2.setEnabled(false);
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox2.setMargin(new java.awt.Insets(20, 0, 0, 0));
        jPanel17.add(jCheckBox2);

        jPanel15.add(jPanel17);

        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setMaximumSize(new java.awt.Dimension(150, 40));
        jFormattedTextField2.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel18.add(jFormattedTextField2);

        jPanel15.add(jPanel18);

        jPanel12.add(jPanel15, java.awt.BorderLayout.NORTH);

        jPanel14.setMinimumSize(new java.awt.Dimension(95, 74));
        jPanel14.setPreferredSize(new java.awt.Dimension(222, 100));
        jPanel14.setLayout(new java.awt.GridLayout(2, 0));

        jPanel19.setPreferredSize(new java.awt.Dimension(356, 40));

        jCheckBox3.setText("Check out");
        jCheckBox3.setEnabled(false);
        jCheckBox3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox3.setMargin(new java.awt.Insets(20, 0, 0, 0));
        jPanel19.add(jCheckBox3);

        jPanel14.add(jPanel19);

        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setMaximumSize(new java.awt.Dimension(150, 40));
        jFormattedTextField1.setMinimumSize(new java.awt.Dimension(150, 40));
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(150, 40));
        jPanel20.add(jFormattedTextField1);

        jPanel14.add(jPanel20);

        jPanel12.add(jPanel14, java.awt.BorderLayout.SOUTH);

        jPanel6.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel13.setPreferredSize(new java.awt.Dimension(222, 60));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel13, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel6);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel21.setMinimumSize(new java.awt.Dimension(100, 35));
        jPanel21.setPreferredSize(new java.awt.Dimension(100, 60));

        jCheckBox4.setText("Customer");
        jCheckBox4.setEnabled(false);
        jCheckBox4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox4.setMargin(new java.awt.Insets(25, 0, 0, 0));
        jPanel21.add(jCheckBox4);

        jPanel5.add(jPanel21, java.awt.BorderLayout.NORTH);

        jPanel22.setPreferredSize(new java.awt.Dimension(280, 183));
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.LINE_AXIS));

        jPanel25.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel25.setPreferredSize(new java.awt.Dimension(80, 0));
        jPanel25.setLayout(new java.awt.GridLayout(5, 1));

        jLabel2.setText("Last Name :");
        jPanel25.add(jLabel2);

        jLabel3.setText("First Name :");
        jPanel25.add(jLabel3);

        jLabel4.setText("Gender :");
        jPanel25.add(jLabel4);

        jLabel5.setText("ID Number :");
        jPanel25.add(jLabel5);

        jLabel6.setText("Telephone :");
        jPanel25.add(jLabel6);

        jPanel22.add(jPanel25);

        jPanel24.setMaximumSize(new java.awt.Dimension(260, 32767));
        jPanel24.setPreferredSize(new java.awt.Dimension(200, 183));
        jPanel24.setLayout(new java.awt.GridLayout(5, 1));

        jTextField1.setText("jTextField1");
        jPanel24.add(jTextField1);

        jTextField2.setText("jTextField2");
        jPanel24.add(jTextField2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        jPanel24.add(jComboBox1);

        jTextField3.setText("jTextField3");
        jPanel24.add(jTextField3);

        jTextField4.setText("jTextField4");
        jPanel24.add(jTextField4);

        jPanel22.add(jPanel24);

        jPanel5.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel23.setMinimumSize(new java.awt.Dimension(100, 40));
        jPanel23.setPreferredSize(new java.awt.Dimension(356, 40));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel23, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel5);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(668, 50));

        jReset.setText("Reset");
        jPanel4.add(jReset);

        jButton3.setText("Confirm");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jButton3);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
